from __future__ import annotations

from pathlib import Path

from thesis_os.arki.vault_writer import VaultWriter
from thesis_os.models import utc_now


VAULT_SECTIONS = {
    "evidence": "Source-grounded facts and interpretations",
    "screeners": "Quantitative candidate outputs",
    "theses": "Living thesis cards",
    "decisions": "Decision cards and action rationale",
    "feedback": "Prediction and screener outcome reviews",
    "alerts": "Intraday holdings and watchlist alerts",
    "dashboard": "Portfolio and thesis cockpit artifacts",
}


def build_wiki_index(workspace: str | Path) -> dict[str, object]:
    workspace = Path(workspace)
    vault_root = workspace / "vault"
    writer = VaultWriter(vault_root)
    writer.ensure_layout()

    section_counts: dict[str, int] = {}
    index_lines = [
        "This index is generated by Arki so agents can find the latest canonical research objects.",
        "",
        "## Sections",
    ]
    for section, description in VAULT_SECTIONS.items():
        files = sorted((vault_root / section).glob("*.md"))
        section_counts[section] = len(files)
        index_lines.append(f"- **{section}** ({len(files)}): {description}")
        for path in files[-5:]:
            index_lines.append(f"  - [[../{section}/{path.name}|{path.stem}]]")

    index_lines.extend(
        [
            "",
            "## Agent Lookup Rule",
            "- Alpha should update `evidence/` and `screeners/`.",
            "- Lattice should read evidence and screeners before updating `theses/`, `decisions/`, and `feedback/`.",
            "- Arki should keep this index, schemas, and SSOT notes current.",
        ]
    )
    index_path = writer.write_note(
        "wiki/index.md",
        title="Thesis OS Wiki Index",
        body="\n".join(index_lines),
        frontmatter={"generated_at": utc_now(), "type": "wiki_index"},
    )

    ssot_body = "\n".join(
        [
            "This note defines canonical locations for public Thesis OS objects.",
            "",
            "## Canonical Object Locations",
            "- Evidence: `vault/evidence/`",
            "- Screener candidates: `vault/screeners/`",
            "- Thesis cards: `vault/theses/`",
            "- Decision cards: `vault/decisions/`",
            "- Feedback reports: `vault/feedback/`",
            "- Dashboards: `vault/dashboard/`",
            "- Wiki index: `vault/wiki/index.md`",
            "",
            "## Freshness Principle",
            "Agents should prefer the newest canonical note for each object and avoid creating duplicate folders for the same role.",
        ]
    )
    ssot_path = writer.write_note(
        "ssot/canonical-locations.md",
        title="Canonical Locations SSOT",
        body=ssot_body,
        frontmatter={"generated_at": utc_now(), "type": "ssot"},
    )
    return {
        "workspace": str(workspace),
        "index_path": str(index_path),
        "ssot_path": str(ssot_path),
        "section_counts": section_counts,
    }
